#!/bin/bash

#PBS -P w97
#PBS -q normalbw
#PBS -l walltime=04:00:00
#PBS -l mem=16GB
#PBS -l ncpus=1
#PBS -l storage=gdata/w97+gdata/hh5+gdata/fj8+gdata/zv2
#PBS -m a
#PBS -M anjana.devanand@unsw.edu.au
#PBS -N lon_concat
#PBS -l wd

#####PBS -j oe
#####PBS -l wd

module use /g/data/hh5/public/modules
module load conda/analysis3

export iWeek=4
export glm_dir=/g/data/w97/ad9701/p_prob_analysis/model_output/awra/GLM_results_model4/
export start_lat=-35.025

python ./concat_files_all_lon.py

