#!/bin/bash

#PBS -P w97
#PBS -q normalbw
#PBS -l walltime=04:00:00
#PBS -l mem=16GB
#PBS -l ncpus=1
#PBS -l storage=gdata/w97+gdata/hh5+gdata/fj8+gdata/zv2
#PBS -m a
#PBS -M anjana.devanand@unsw.edu.au
#PBS -N lon_concat
#PBS -l wd

#####PBS -j oe
#####PBS -l wd

module use /g/data/hh5/public/modules
module load conda/analysis3

export iWeek=6
export glm_dir
export start_lat

python ./concat_files_all_lon.py

